name = "SemanticRelease"
uuid = "2efb228a-ba02-4e80-87a4-7dd62bc882d1"
authors = ["Tim Wilson <twilsonco@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
