name: commitlint

on: 
  push:
    branches: [master]

jobs:
      
  commitlint:  
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v2
    
    - name: Set up Node.js
      uses: actions/setup-node@v2

    - name: Install commitlint 
      run: npm install @commitlint/config-conventional @commitlint/cli

    - name: Fetch full git history
      run: git fetch --prune --unshallow
    
    - name: Lint commit messages 
      env:
        REPORT_COMMENTS: true 
      run: npx commitlint --from HEAD~1 --verbose