name: PR Title

on: 
  pull_request:
    types: [opened, edited, reopened, synchronized]
      
jobs:

  conventional_title:

    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v3

    - name: Conventional PR Title
      uses: aslafy-z/conventional-pr-title-action@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}